[cosmopolitan]
git-tree-sha1 = "6f69aab84d81d162aa713bd3705362d978ef9663"
lazy = true

    [[cosmopolitan.download]]
    url = "https://github.com/brenhinkeller/cosmopolitan-artifact-mirror/raw/main/archives/cosmopolitan-amalgamation-2.1.1.tar.gz"
    sha256 = "42148b33aa6eff7464626bde4411e47a69194754d85b21b5a659889548fea9a3"


[cosmopolitan-tiny]
git-tree-sha1 = "1a170287e144002b65d37ef662fb7fcda1907a89"
lazy = true

    [[cosmopolitan-tiny.download]]
    url = "https://github.com/brenhinkeller/cosmopolitan-artifact-mirror/raw/main/archives/cosmopolitan-amalgamation-tiny-2.1.1.tar.gz"
    sha256 = "33c7edda69b61f34e378d8d0e1b7c8d44a9e69865aa4ceb04592a0dd2db79ebe"
